config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  root "home#index"

  namespace :api do
    resources :teams, only: %i[index show create update destroy]
    resources :exploits, only: %i[index show create update destroy]
    resources :flags, only: %i[index create]
  end

  resources :teams, except: %i[show]
  resources :exploits
  resources :flags, only: %i[index new create]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/flag.rb
# frozen_string_literal: true

class Flag < ApplicationRecord
  belongs_to :team, optional: true
  belongs_to :exploit, optional: true

  validates :content, :pts, presence: true
  validates :content, uniqueness: true

  enum status: { initial: 0, accepted: 1, already_posted: 2, too_old: 3, our_own: 4 }
end

app/controllers/api/flags_controller.rb
# frozen_string_literal: true

class Api::FlagsController < ApiController
  def index
    @flags = Flag.all
  end

  def create
    @flag = Flag.new(permitted_params)

    respond_to do |format|
      if @flag.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def permitted_params
    params.fetch(:flag, {}).permit(:content)
  end
end

app/controllers/flags_controller.rb
# frozen_string_literal: true

class FlagsController < UiController
  before_action :set_flag, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: FlagDatatable.new(params) }
    end
  end

  def show; end

  def new
    @flag = Flag.new
  end

  def edit; end

  def create
    @flag = Flag.new(permitted_params)

    respond_to do |format|
      if @flag.save
        format.html { redirect_to @flag, notice: "Flag was successfully created." }
        format.json { render :show, status: :created, location: @flag }
      else
        format.html { render :new }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @flag.update(permitted_params)
        format.html { redirect_to @flag, notice: "Flag was successfully updated." }
        format.json { render :show, status: :ok, location: @flag }
      else
        format.html { render :edit }
        format.json { render json: @flag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @flag.destroy!
    respond_to do |format|
      format.html { redirect_to flags_url, notice: "Flag was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_flag
    @flag = Flag.find(params[:id])
  end

  def permitted_params
    params.fetch(:flag, {})
  end
end

app/views/flags/_form.html.erb
<%= form_with(model: flag, local: true) do |form| %>
  <% if flag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flag.errors.count, "error") %> prohibited this flag from being saved:</h2>

      <ul>
      <% flag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/flags/edit.html.erb
<h1>Editing Flag</h1>

<%= render 'form', flag: @flag %>

<%= link_to 'Show', @flag %> |
<%= link_to 'Back', flags_path %>

app/views/flags/index.html.slim
= render(partial: 'partials/flags')

app/views/flags/new.html.erb
<h1>New Flag</h1>

<%= render 'form', flag: @flag %>

<%= link_to 'Back', flags_path %>

app/views/flags/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_flag_path(@flag) %> |
<%= link_to 'Back', flags_path %>