config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :users
  root "home#index"

  namespace :api do
    resources :teams, only: %i[index show create update destroy]
    resources :exploits, only: %i[index show create update destroy]
    resources :flags, only: %i[index create]
  end

  resources :teams, except: %i[show]
  resources :exploits
  resources :flags, only: %i[index new create]

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
end

app/models/exploit.rb
# frozen_string_literal: true

class Exploit < ApplicationRecord
  has_and_belongs_to_many :teams
  has_many :flags

  validates :source, :period, :timeout, :title, presence: true

  enum status: { down: 0, up: 1 }

  after_save { Engine::Exploit::AfterSave.call(self) }
  before_destroy { Engine::Exploit::BeforeDestroy.call(self) }
end

app/controllers/api/exploits_controller.rb
# frozen_string_literal: true

class Api::ExploitsController < ApiController
  before_action :set_exploit, only: [:show, :update, :destroy]

  def index
    @exploits = Exploit.all
  end

  def show; end

  def create
    @exploit = Exploit.new(exploit_params)

    respond_to do |format|
      if @exploit.save
        format.json { render :show, status: :created }
      else
        format.json { render json: @exploit.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @exploit.update(permitted_params)
        format.json { render :show, status: :ok }
      else
        format.json { render json: @exploit.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @exploit.destroy!
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  def set_exploit
    @exploit = Exploit.find(params[:id])
  end

  def permitted_params
    params.fetch(:exploit, {}).permit(:source, :period, :timeout, :title)
  end
end

app/controllers/exploits_controller.rb
# frozen_string_literal: true

class ExploitsController < UiController
  before_action :set_exploit, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: ExploitDatatable.new(params) }
    end
  end

  def show; end

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @exploit = Exploit.new(permitted_params)

    if @exploit.save
      include_for_all_teams if included?
      respond_to do |format|
        format.html { redirect_to exploits_path }
      end
    else
      head :unprocessable_entity
    end
  end

  def update
    if @exploit.update(permitted_params)
      include_for_all_teams if included?

      respond_to do |format|
        format.html { redirect_to exploits_path }
      end
    else
      head :unprocessable_entity
    end
  end

  def destroy
    @exploit.destroy!
    head :no_content
  end

  private

  def set_exploit
    @exploit = Exploit.find(params[:id])
  end

  def permitted_params
    params
      .fetch(:exploit, {})
      .permit(:title, :source, :status, :period, :timeout, :included)
      .yield_self { |params| Utils.with_numeric_status(params) }
  end

  def included?
    params.key?(:included)
  end

  def include_for_all_teams
    Team.all.each do |team|
      @exploit.teams << team unless @exploit.teams.include?(team)
    end
  end
end

app/views/exploits/_edit.html.slim
div id="edit-modal" class="modal hide fade" role="dialog"

app/views/exploits/_form.html.slim
div class="modal-dialog modal-lg" role="document"
  div class="modal-content"
    div class="m-3"
      = form_for exploit || Exploit.new do |f|
        div class="modal-header"
          h5 class="modal-title" = exploit.presence ? 'Edit Exploit' : 'New Exploit'
          button type="button" class="close" data-dismiss="modal"
            span aria-hidden="true">&times;
        div class="modal-body"
          div class="form-group"
            = f.label :title, 'Title'
            = f.text_field :title, class: 'form-control'
          div class="form-group"
            = f.label :period, 'Period'
            = f.text_field :period, class: 'form-control'
          div class="form-group"
            = f.label :timeout, 'Timeout'
            = f.text_field :timeout, class: 'form-control'
          div class="form-group"
            = f.label :source, 'Source'
            = f.text_area :source, class: 'form-control'
          div class="form-group"
            = f.label :status, 'Status'
            = f.select :status, Exploit.statuses.keys.map { |w| [w.humanize, w] }, {}, { class: 'form-control' }
          div class="form-check"
            = check_box_tag :included, :y, false, class: 'form-check-input'
            = label_tag :included, 'Include For All Teams', class: 'form-check-label'
        div class="modal-footer"
          = f.submit 'Save', class: 'btn btn-primary'
          button type="button" class="btn btn-secondary" data-dismiss="modal" Close

  javascript:
    var editor = CodeMirror.fromTextArea(
      document.getElementById('exploit_source'),
      {
        lineNumbers: true,
        autoRefresh: true,
        indentUnit: 2,
        tabSize: 2,
        theme: 'night'
      });

app/views/exploits/_new.html.slim
div id="new-modal" class="modal hide fade" role="dialog"

app/views/exploits/edit.html.erb
<h1>Editing Exploit</h1>

<%= render 'form', exploit: @exploit %>

<%= link_to 'Show', @exploit %> |
<%= link_to 'Back', exploits_path %>

app/views/exploits/edit.js.erb
$("#edit-modal").html("<%= j render 'form', exploit: @exploit %>");
$("#edit-modal").modal();

app/views/exploits/index.html.slim
= render(partial: 'partials/exploits')

app/views/exploits/new.html.erb
<h1>New Exploit</h1>

<%= render 'form', exploit: @exploit %>

<%= link_to 'Back', exploits_path %>

app/views/exploits/new.js.erb
$("#new-modal").html("<%= j render 'form', exploit: @exploit %>");
$("#new-modal").modal();

app/views/exploits/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_exploit_path(@exploit) %> |
<%= link_to 'Back', exploits_path %>